#!/usr/bin/env python
# create a "histogram" of categories in the modis_landuse_30s
# 19-category land use dataset (~/wrf/geog/modus_landuse_30s).
# looks at each 1200x1200 tile individually and counts up each
# land use category number.  outputs percentages to stdout at end.
# there are 648 tiles, so this takes a little while.

import pdb, numpy
from glob import *
#pdb.set_trace()

cats = range( 1, 21 ) # 1-20 just in case there really are 20 categories
cnt = numpy.zeros( len(cats)+1, dtype=numpy.int )

#ifn = "00001-01200.00001-01200"
fpatt = "?????-*"
flist = glob( fpatt )

i = 1
for ifn in flist:
  print str(i)+" "+ifn
  x = numpy.fromfile(ifn,numpy.int8,-1,"")

  for c in cats:
    y = numpy.where( x == c )
    cnt[c] = cnt[c] + len(y[0])
  i += 1

tot = sum(cnt)
for c in cats:
  pct = float(cnt[c]) / float(tot) * 100.
  s = "%d: %3.3f" % (c, pct)
  print s
