#!/usr/bin/env python
import pdb, sys, os, commands

nargin = len( sys.argv )
if nargin < 2:
  print "Usage:  check_netcdf file_list"
  print "  Look at the Time var in metgrid output to see if it's valid"
  print "  file_list - list of files to examine"
  sys.exit()

file_list = sys.argv[1]
ifile = open( file_list, "r" )
files = ifile.readlines()
ifile.close()

#pdb.set_trace()
for ff in files:
  f = ff.rstrip()
  cmd = "ncdump -h "+f+" | grep currently"
  txt = commands.getoutput( cmd )
  aa = txt.split(" ")[5]
  bb = int(aa[-1])
  if bb == 0:
    aa = f.split('/')[3]
    print aa
