#!/usr/bin/env python
# purge_wrf_hpss:
# create a shell script to delete all spinup files found in the 
# wrf HPSS archive directories.

import pdb, sys, os

nargin = len(sys.argv)
if nargin < 3:
  print "Syntax:  purge_wrf_hpss ifn ofn"
  print "  ifn = name of file with HPSS file list"
  print "  ofn = name of shell script file for delete commands"
  sys.exit()

# get list of files to process
ifn = sys.argv[1]
ifile = open( ifn, "r" )
file_list = ifile.readlines()
ifile.close()

# open output file
ofn = sys.argv[2]
ofile = open( ofn, "w" )
ofile.write( "#!/bin/csh\n\n" )
ofile.write( "cat << EOF > temp_file_list\n" )

for fp in file_list:
  a = fp.split('/')
  dir_date = a[-2]
  wrfname = a[-1]
  yy = wrfname[11:15]
  mm = wrfname[16:18]
  dd = wrfname[19:21]
  file_date = yy+mm+dd
  if dir_date == file_date:
    ofile.write( "rm "+fp )

ofile.write( "EOF\n" )
# use followimg to direct command output to a file
#ofile.write( 'hsi "out > hsi_out ; in temp_file_list"\n' )
ofile.write( 'hsi "in temp_file_list"\n' )
ofile.write( "rm temp_file_list\n" )
ofile.close()
