#!/usr/bin/env python
import pdb
import sys, os
from glob import *

nargin = len( sys.argv )
if nargin < 2:
  print "Usage:  save_rsl prefix [dir]"
  print "  Save rsl files by adding prefix"
  print "  Optionally move to a specific directory"
  sys.exit( 0 )
else:
  new_prefix = sys.argv[1]
s = "Saving rsl files from "+new_prefix

dir_pref = "./"
if nargin > 2:
  new_dir = sys.argv[2]
  s = s+" in directory "+new_dir
  dir_pref = "../"
  if not os.path.exists( new_dir ):
    os.mkdir( new_dir )
  os.chdir( new_dir )

print s

# save "error" files
filepat = dir_pref+'rsl.error.????'
files = glob( filepat )
#pdb.set_trace()
for f in files:
  g = f.split('/')
  if len(g) > 1:
    h = g[1]
  else:
    h = g
  new_f = new_prefix+"_"+h
  cmd = "mv "+f+" "+new_f
#  print cmd
  try:
    os.system( cmd )
  except OSError,msg:
    print OSError, msg

# save "out" files
filepat = dir_pref+'rsl.out.????'
files = glob( filepat )
for f in files:
  g = f.split('/')
  if len(g) > 1:
    h = g[1]
  else:
    h = g
  new_f = new_prefix+"_"+h
  cmd = "mv "+f+" "+new_f
#  print cmd
  try:
    os.system( cmd )
  except OSError,msg:
    print OSError, msg
