#!/usr/bin/env python
# wrf_postproc_ccsm
# run wrf_postproc.ncl on a specific file
# output goes to a directory matching yy/mm/dd of input file

import pdb, sys, os

#pdb.set_trace()
nargin = len(sys.argv)
if nargin < 2:
  print "Syntax:  wrf_postproc_ccsm input_fn subdir period"
  print "  input_fn = name of wrfout file to be processed"
  print "  subdir = intermediate dir path (e.g., ccsm)"
  print "  period = intermediate dir path (e.g., 20th.track1)"
  sys.exit()

# get command line args
input_fn = sys.argv[1]

if nargin < 3:
  subdir = ""
else:
  subdir = sys.argv[2]
if nargin < 4:
  period = ""
else:
  period = sys.argv[3]

# ncl command
ncl_cmd = "/glade/u/home/dbr/wrf/ncl/wrfout_postproc.ncl"

# split filename and gather yy/mm/dd info
dir_tmp = os.path.dirname( input_fn )
file_in = os.path.basename( input_fn )
file_yy = file_in[ 11:15 ]
file_mm = file_in[ 16:18 ]
file_dd = file_in[ 19:21 ]

# convert hpss dir_in to scratch dir_in
a = dir_tmp.split('/')
dir1 = a[-2]
dir2 = a[-1]
if len(subdir) > 0:
  base = "/glade/scratch/dbr/wrf/"+subdir+"/"+period+"/run/"
else:
  base = "/glade/scratch/dbr/wrf/run/"
dir_in = base+dir1+"/"+dir2+"/"

# output names
if len(subdir) > 0:
  dir_out = "/glade/scratch/dbr/wrf/%s/%s/postproc/%s/%s%s%s/" % (subdir, period, file_yy, file_yy, file_mm, file_dd)
else:
  dir_out = "/glade/scratch/dbr/wrf/postproc/%s/%s%s%s/" % (file_yy, file_yy, file_mm, file_dd)
file_out = file_in+".nc"
ofn = dir_out+file_out
if os.path.exists( ofn ):
  os.unlink( ofn )

if not os.path.exists( dir_out ):
  try:
    os.makedirs( dir_out )
  except OSError:
    pass
#    print "Caught makedir of existing dir "+dir_out

arg1 = "'dir_in=\""+dir_in+"\"'"
arg2 = "'file_in=\""+file_in+"\"'"
arg3 = "'dir_out=\""+dir_out+"\"'"
arg4 = "'file_out=\""+file_out+"\"'"
cmd = "ncl "+arg1+" "+arg2+" "+arg3+" "+arg4+" "+ncl_cmd
os.system( cmd )
